### ISSUE TITLE
Repositorio para temas generales

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#1]
@codersmexico/admins me tome la libertad de crear este repo nuevo para tener aquí los issues generales, como el código de conducta, cambios a Slack, nuevos proyectos, etc.

También estoy copiando algo que nos ha funcionado en mi proyecto que es tener diferentes labels para organizar los issues.

Voy a ir haciendo algunos issues de cosas que he visto y considero que podríamos trabajar.

@poguez espero no estarme adelantando a la platica de bienvenida 😨

**Comment by shelldandy** [comment]
🎉
