### ISSUE TITLE
Código de conducta

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#10]
El original esta en codersmexico/codigo-conducta#1.

Necesitamos un código de conducta para la comunidad (Slack, eventos, paginas, proyectos, etc.).

Las propuestas actuales son:

- Código de conducta de Python
- Contributor Covenant

**Comment by poguez** [comment]
**Accionables**
- [x] Introducir ejemplos del de python al de Code Convenant
- [x] Correo de conducta@codersmexico.com
- [x] Review/Vobo. de todos los admins a la versión final.
  - [x] @mike3run 
  - [x] @eruizdechavez 
  - [ ] @diegoaguilar 
  - [x] @zunware 
  - [x] @ratacibernetica
  - [x] @poguez

**Comment by shelldandy** [comment]
En calor hay que shippear aunque sea un beta de esto pero yaaaaaaaa @poguez

**Comment by poguez** [comment]
@eruizdechavez @mike3run 
Agregué la versión que @eruizdechavez había propuesto. Está en codersmexico/codigo-conducta.

Creo que hace falta agregar:
**Manual de Ejecución**: 
https://www.djangoproject.com/conduct/enforcement-manual/
**Lineamientos de Reporte**
https://www.djangoproject.com/conduct/reporting/

**Propongo:** mejor agregarlos en Issues separados.

**Comment by eruizdechavez** [comment]
Suena bien @poguez.

@codersmexico/admins tengo una duda... sera bueno que tengamos multiples repos con el disclaimer, código de conducta, etc., o será mejor consolidar en un solo repo?

**Comment by poguez** [comment]
@eruizdechavez Yo creo que uno y hay que referirlo en lo demás que hagamos.

**Comment by eruizdechavez** [comment]
Ya esta listo un pull request #13 con los cambios para consolidar los dos documentos que tenemos en este repo.

**Comment by eruizdechavez** [comment]
@codersmexico/admins ping

**Comment by shelldandy** [comment]
Check

**Comment by eruizdechavez** [comment]
Cerrando issue al tener mayoría. Documentos agregados en codersmexico/docs.
