### ISSUE TITLE
Disclaimer para #compra-venta

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#11]
El canal #compra-venta permite a las personas de la comunidad anunciar bienes y/o servicios que no necesariamente son proporcionados ni avalados oficialmente. Al tener este canal alguien podria aprovecharse del medio y obtener dinero de forma que afecte a otras personas lo cual podria de alguna forma afectarnos o involucrarnos.

**Propuesta**: Agregar algún tipo de disclaimer, probablemente en el subject o con un bot al entrar al canal en el cual se deja claro básicamente que nos deslindamos de cualquier responsabilidad de dichas ventas/servicios/etc.

**Comment by shelldandy** [comment]
@eruizdechavez para overlord de los admins pl0x puras buenas propuestas caray

**Comment by shelldandy** [comment]
Tomado de los TyC de MercadoLibre creo que aplica perfecto este párrafo:

http://ayuda.mercadolibre.com.mx/ayuda/terminos-y-condiciones-uso-del-sitio_2090

MercadoLibre sólo pone a disposición de los Usuarios un espacio virtual que les permite ponerse en comunicación mediante Internet para encontrar una forma de vender o comprar bienes y/o servicios. Mercado Libre no es el propietario de los artículos ofrecidos, no tiene posesión de ellos ni los ofrece en venta. Mercado Libre no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no será responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los Usuarios, así como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los artículos que publica para su venta y por las ofertas y/o compras que realiza.
Debido a que Mercado Libre no tiene ninguna participación durante todo el tiempo en que el artículo se publica para la venta, ni en la posterior negociación y perfeccionamiento del contrato definitivo entre las partes, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operación. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ningún caso Mercado Libre será responsable por lucro cesante, o por cualquier otro daño y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por artículos publicados a través de MercadoLibre.
MercadoLibre recomienda actuar con prudencia y sentido común al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, además, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. Mercado Libre NO será responsable por la realización de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por MercadoLibre.

**Comment by shelldandy** [comment]
Un simple search and replace quitamos ML y ponemos Coders México

**Comment by shelldandy** [comment]
Coders México sólo pone a disposición de los Usuarios un espacio virtual que les permite ponerse en comunicación mediante Internet para encontrar una forma de vender o comprar bienes y/o servicios. Coders México no es el propietario de los artículos ofrecidos, no tiene posesión de ellos ni los ofrece en venta. Coders México no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no será responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los Usuarios, así como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los artículos que publica para su venta y por las ofertas y/o compras que realiza.
Debido a que Coders México no tiene ninguna participación durante todo el tiempo en que el artículo se publica para la venta, ni en la posterior negociación y perfeccionamiento del contrato definitivo entre las partes, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operación. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ningún caso Coders México será responsable por lucro cesante, o por cualquier otro daño y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por artículos publicados a través de Coders México.
Coders México recomienda actuar con prudencia y sentido común al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, además, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. Coders México NO será responsable por la realización de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por Coders México.
En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a Coders México.

**Comment by shelldandy** [comment]
Para hacer el bot que te dice eso al unirte a compra-venta sería con esto:

https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5

Le podrían echar un ojo @poguez o @eruizdechavez ???

Como no tengo heroku me da flojera configurarlo pero si ya tienen cuenta se ve muy rápido de hacer

**Comment by eruizdechavez** [comment]
Yo lo reviso en la noche. ChilangoBot ya está en el canal, solo tengo que meter la lógica, o si alguien se anima, pueden mandarme un pull request.

**Comment by poguez** [comment]
@mike3run @eruizdechavez creo que hace falta mencionar que el consejo de administradores nos reservamos el derecho de suspender algún anuncio. Todos los anuncios están sujetos al Código de Convivencia(CoC) y el lenguaje de los anuncios deben de conformarse a él.

**Comment by shelldandy** [comment]
Listo, creo que lo más saludable es mandar PR acá:

https://github.com/codersmexico/disclaimer-compra-venta

**Comment by shelldandy** [comment]
Ya voy a cerrar acá ❤️
