### ISSUE TITLE
Configurar servidor de correos

### ISSUE THREAD

**Issue by poguez** [codersmexico/codersmexico#12]
Configurar los correos del dominio para administradores.

**Comment by poguez** [comment]
Confirmen que funciona:
- [x] @mike3run 
- [x] @eruizdechavez 
- [x] @zunware 
- [x] @diegoaguilar 
- [x] @ratacibernetica 
- [x] @poguez

**Comment by ratacibernetica** [comment]
@poguez no puedo entrar con:

email: martin@
pass:  default

:P

**Comment by josellausas** [comment]
@ratacibernetica el password default es: "codersmexico"

**Comment by josellausas** [comment]
@poguez Podemos tener SMTP habilitado?

**Comment by eruizdechavez** [comment]
@zunware los servicios POP, IMAP y SMTP se habilitan por cuenta según recuerdo
