### ISSUE TITLE
Agregar manual de ejecución para el código de conducta

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#14]
Manual de Ejecución:
https://www.djangoproject.com/conduct/enforcement-manual/

**Comment by ratacibernetica** [comment]
_Primer borrador:_
[PR](https://github.com/codersmexico/docs/pull/1)

**Comment by eruizdechavez** [comment]
@ratacibernetica en vez de ponerlo como comentario, te recomiendo que mejor lo mandes como un pull request con un archivo Markdown a https://github.com/codersmexico/docs, así podemos contribuir y ver los cambios ;)

**Comment by ratacibernetica** [comment]
Hecho @eruizdechavez .
Sobre ese borrador podemos ir moldeando como consideremos mejor. 🙂

**Comment by eruizdechavez** [comment]
Gracias @ratacibernetica! Para referencia el pull request es codersmexico/docs#1

**Comment by ratacibernetica** [comment]
cerrando en espera de resolución del PR https://github.com/codersmexico/docs/pull/1
