### ISSUE TITLE
ChilangoBot: ¿cómo deberíamos llamarlo?

### ISSUE THREAD

**Issue by poguez** [codersmexico/codersmexico#18]
ChilangoBot necesita un nombre que se identifique con la comunidad.

Nuestro bot se convertirá en nuestro asistente para para guardar links que hayamos compartido y ayudar con algunas tareas informativas en la comunidad. Nuestro bot posteriormente se encargará de guardar y republicar algunos de los links que compartamos en la comunidad.

¿Cómo lo llamarías? y ¿por qué?

**Comment by shelldandy** [comment]
Solín como el asistente de Kaliman

**Comment by diegoaguilar** [comment]
Creo, no sería mala idea viajarse con unos 4-6 nombres y lanzarlo a votación pública. Llama la atención, se rompe el hielo con la gente, y tenemos _un nuevo bot_.

**Comment by poguez** [comment]
Podemos usar, tiene un algoritmo:
http://www.allourideas.org/

**Comment by pazthor** [comment]
ABS©
Another Bot for Safe content

**Comment by shelldandy** [comment]
ABfSC iugh

**Comment by josellausas** [comment]
"Poguy" o "Poggy" o "Pogbot" (Por la leyenda de aquel misterioso usuario que manda a los chistositos a random)

O ya de plano: "Masiosare"

**Comment by pazthor** [comment]
Si es de elegir, yo me voy por *PogBot* .
Porque eso de llevar casi 7 meses para elegir un nombre como que no. jaja

**Comment by shelldandy** [comment]
`Pogbot` va va
