### ISSUE TITLE
Default Channels

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#2]
Al entrar, un usuario es asignado a muchos canales por default. Independientemente de la limpieza de canales que se haga, no estoy seguro de que sea bueno meter a los usuarios a todos los canales.

<img width="749" alt="screen shot 2017-04-19 at 12 56 58 pm" src="https://cloud.githubusercontent.com/assets/953140/25194359/d746659c-24ff-11e7-8e62-8016efb64d43.png">

**Propuesta**: Después de la limpieza de canales, definir 2 o 3 canales que sean buenos puntos de entrada como `general`, `ayuda`, etc.

**Comment by shelldandy** [comment]
obvio `#human-x-interaction` aka `#maestria-de-poguez` es el adecuado

Nah, pero en serio creo que recomendaría agregar por default a:

- General
- Ofertas de trabajo
- Javascript o Frontend (mi razonamiento de esas es porque son muuuy usadas y aparte más probable que alguien que recién inicia solo conozca una de esas opciones)
- Random

Quizá
- Comparte música

Fin

**Comment by poguez** [comment]
*Propuesta:* hacer una votación con los canales con más usuarios activos. Después elegir 10 canales principales por defecto para nuevos usuarios.

**Comment by eruizdechavez** [comment]
Update: `ChilangoBot` ya esta en todos los canales (tiene un par de issues en las noches, pero ya lo estoy revisando). En un par de semanas deberíamos tener datos de que canales están moviéndose y que canales no.

**Comment by eruizdechavez** [comment]
<img width="276" alt="screen shot 2017-05-05 at 9 00 27 am" src="https://cloud.githubusercontent.com/assets/953140/25748655/71116bb8-3171-11e7-92ea-768c4f19524d.png">

**Comment by eruizdechavez** [comment]
Ahora que tenemos reducida la lista de canales a 31, cuales van a ser los canales por default?

Lista de canales:

- algoritmos
- android
- arquitectura-software
- cine-y-series
- coders-puebla
- comida-y-bebidas
- comparte-musica
- compra-venta
- cybersecurity
- design
- dotnet
- elixir
- eventos
- filosofia-y-libros
- front-end
- general
- golang
- inteligenciaartificial
- java
- javascript
- linux
- mobile
- ofertas-de-empleo
- open-english
- php
- python
- random
- ruby-lang
- rust
- scala
- work-life

**Comment by eruizdechavez** [comment]
Mi propuesta para los canales default es la siguiente:

- general
- random
- work-life
- open-english
- javascript
- front-end
- eventos
- cine-y-series
- compra-venta
- ofertas-de-empleo

**Comment by poguez** [comment]
Why javascript y los otros lenguajes no 😛

Tenemos 31 canales ahora... hay que tomar en cuenta que si vamos a dar un mínimo de canales por defecto deberíamos de dar una guía con la lista de todos los canales por slackbot para que la gente conozca todos. Esto es relacionado al problema que les decía que hay gente que cuando entra no sabe que hay otros canales.

**Comment by diegoaguilar** [comment]
Creo que será cuento de nunca acabar (ok, es una expresión) el discutir los default channels, sobre todo si intentamos definir _un conjunto_. Así que para ser prácticos, pondría los básicos como `#general`, `#random`, `#eventos`, y tal y como ha sugerido @poguez una lista de todos los canales públicos por parte de Slackbot.

**Comment by eruizdechavez** [comment]
@poguez aunque usted no lo crea originalmente javascript no estaba en mi propuesta inicial, pero después me puse a ver los mensajes por canal y se me ocurrió incluirlo pues fue de los más activos. 

Estoy de acuerdo en quitarlo y poner una lista completa en el bot o en un mensaje de bienvenida.

**Comment by mike3run** [comment]
- general
- random
- work-life
- javascript
- front-end
- eventos
- ofertas-de-empleo

**Comment by ratacibernetica** [comment]
- general
- random
- work-life
- open-english 
- javascript
- front-end
- eventos
- ofertas-de-empleo

**Comment by poguez** [comment]
Mi propuesta de canales:
- general
- random
- work-life
- open-english
- front-end
- arquitectura-de-software
- eventos
- inteligenciartificial
- comparte-musica
- ofertas-de-empleo

**Comment by diegoaguilar** [comment]
Mi propuesta de canales:
- general
- random
- work-life
- front-end
- arquitectura-de-software
- eventos
- ofertas-de-empleo

**Comment by shelldandy** [comment]
general
random
Work-life
Javascript
open-english
front-end
Eventos
Ofertas-de-empleo
