### ISSUE TITLE
Crear un end-point para aceptar los formularios de trabajos y guardarlos en base de datos.

### ISSUE THREAD

**Issue by poguez** [codersmexico/codersmexico#26]
- Crear un end-point para aceptar un nuevo listado de trabajo.
- Agregarle al modelo un campo de moderación.
 
Ver #23 para crear el json.

**Comment by josellausas** [comment]
Endpoint creado. Ver channel de admins para el URL...

![screen shot 2018-04-11 at 9 27 34 pm](https://user-images.githubusercontent.com/4162671/38653200-345f3d4c-3dcf-11e8-9181-4e55689b6060.png)
