### ISSUE TITLE
Permitir invitaciones

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#3]
Actualmente la forma de registrarse en Coders Mexico es mediante el Slackin. En un par de ocaciones ha demostrado no ser fiable al 100% (se cae, no se envían los correos, etc.).

**Propuesta**: Dado que la comunidad es abierta, porque no permitir a los usuarios invitar a sus conocidos independiente mente de mantener la instancia de Slackin corriendo.

<img width="924" alt="screen shot 2017-04-19 at 1 00 24 pm" src="https://cloud.githubusercontent.com/assets/953140/25194576/7d5ca7e8-2500-11e7-8ada-c7542ee3f845.png">

**Comment by shelldandy** [comment]
Done
