### ISSUE TITLE
Modificar cuando se puede editar/borrar un mensaje

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#4]
Por default, en Slack los mensajes pueden ser borrados/editados en cualquier momento. En general esto no debería ser un problema, pero para determinados mensajes que violaran el código de conducta podría volver difícil el investigar o validar un reporte.

<img width="930" alt="screen shot 2017-04-19 at 1 10 20 pm" src="https://cloud.githubusercontent.com/assets/953140/25195016/f25c3058-2501-11e7-98c3-3f954c37f1f5.png">

**Propuesta**: Cambiar el tiempo que permite editar un mensaje de "Siempre" a 24 horas o menos. Editar o borrar un mensaje de hace 1 día puede incluso volver difícil seguir una conversación interesante.

**Notas**: También podríamos implementar un bot que lleve registro de las conversaciones de los canales en los que se encuentre; esto también funcionaria como un log para otros usos, como estadísticas, listado de links, etc.

**Comment by poguez** [comment]
**Propuesta**: 24 horas.

**Comment by ratacibernetica** [comment]
Done.

![slack settings](http://res.cloudinary.com/ratacibernetica/image/upload/v1493512423/Screen_Shot_2017-04-29_at_8.32.42_PM_fnxc0n.png)
