### ISSUE TITLE
Elevar permisos para emojis personalizados / mensajes de carga

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#5]
Similar a #4, permitir que todos puedan agregar mensajes de carga o emojis puede caer en situaciones difíciles que violen el código de conducta.

<img width="926" alt="screen shot 2017-04-19 at 1 10 30 pm" src="https://cloud.githubusercontent.com/assets/953140/25195325/e8ab0934-2502-11e7-82d0-bd5520066857.png">

**Propuesta**: Restringir el agregar dicho contenido a solo admins.

**Comment by shelldandy** [comment]
10000% de acuerdo, aparte creo que ya pasó una vez que hubo un mal emoji jaja

que solo los admin puedan

**Comment by diegoaguilar** [comment]
Listo calixto
