### ISSUE TITLE
Elevar permisos para respuestas de Slackbot

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#6]
Slackbot es algo que prácticamente no usamos y podríamos sacarle mas provecho. Para esto mismo y relacionado a #4 y #5, pero dado que cualquiera puede agregar sus propias respuestas, esto podría caer en mal uso o abuso.

<img width="920" alt="screen shot 2017-04-19 at 1 10 41 pm" src="https://cloud.githubusercontent.com/assets/953140/25195477/5d249aaa-2503-11e7-9f16-c34026bae5ab.png">

**Propuesta**: Elevar los permisos para agregar respuestas de Slackbot a solo admins.

**Comment by shelldandy** [comment]
Ahh más bien esto fue lo que se abusó en el pasado no los emojis que mencioné en #5 tipo si decías react, decía ay estos hipsters y mencionaba a @poguez lololol

**Comment by shelldandy** [comment]
Done
