### ISSUE TITLE
Requerir 2FA a los admins

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#7]
En esto me incluyo. Todos los admins de Slack deberíamos tener activo 2FA y ninguno de nosotros lo tiene. Solo 2 usuarios (inactivos) tienen activada esta opción.

<img width="393" alt="screen shot 2017-04-19 at 1 26 26 pm" src="https://cloud.githubusercontent.com/assets/953140/25195620/cea3c28c-2503-11e7-8428-60cd45aea52a.png">

- [x] diegoaguilar
- [x] digaresc
- [x] eruizdechavez
- [x] josellau
- [x] mike
- [x] poguez
- [x] ratacibernetica

**Comment by shelldandy** [comment]
lol me parece bien

**Comment by poguez** [comment]
**Propuesta:** utilicen alguna herramienta para hacer backup de las keys.

**Comment by shelldandy** [comment]
Link directo papus:
https://codersmexico.slack.com/account/settings#two_factor

**Comment by josellausas** [comment]
Ya quedó el mío! Aquí está mi QR.... jajajaja no
