### ISSUE TITLE
Depurar Integraciones

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#8]
No se si existe una forma de restringir quienes pueden agregar integraciones al Slack, pero en mi opinion no cualquiera deberia poder agregarlas.

<img width="1013" alt="screen shot 2017-04-19 at 1 28 53 pm" src="https://cloud.githubusercontent.com/assets/953140/25195787/529b459c-2504-11e7-8136-14beb10d2940.png">

**Propuesta**: Deberiamos revisar cuales de todas las de abajo están en uso y quitar las que no.

<img width="706" alt="screen shot 2017-04-19 at 1 30 38 pm" src="https://cloud.githubusercontent.com/assets/953140/25195821/684376a8-2504-11e7-800d-276b1caba2c8.png">

**Comment by shelldandy** [comment]
![screen shot 2017-04-29 at 11 27 34](https://cloud.githubusercontent.com/assets/7088511/25557064/deb9e322-2cce-11e7-82f2-f37e1895addb.png)

Listo, todavía creo que se podría quitar la integración de Trello y la de Twitter pero lo dejo a criterio de @poguez así que asigno issue a él y está en libertad de quitarlas o no y ya cerrar acá

**Comment by shelldandy** [comment]
Ya cerré todas ALV menos el Hubot.

De trello solo queda 1 inactiva que la puede quitar Angélica ya le pedí así que a esperar
