### ISSUE TITLE
Limpieza de canales

### ISSUE THREAD

**Issue by eruizdechavez** [codersmexico/codersmexico#9]
Creado originalmente por @zunware en codersmexico/codigo-conducta#3. Relacionado a #2.

Actualmente tenemos 70+ canales muchos de los cuales no tienen actividad, son redundantes o simplemente serian mejor consolidados en temas mas generales.

**Propuesta**: "Merge and reduce" los canales de slack. Se comentaba entre los admins el objetivo de reducirlo a ~10 channels.

**Votación**

| Canal                    |  @poguez  | @diegoaguilar | @eruizdechavez | @mike3run | @ratacibernetica |  @zunware  |
| ------------------------ | :-------: | :-----------: | :------------: | :-------: | :--------------: | :--------: |
| `algoritmos`             |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :-1:    |
| `android`                |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `arquitectura-software`  |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `cine-y-series`          |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `coders-puebla`          |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `comida-y-bebidas`       |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `comparte-musica`        |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `cybersecurity`          |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `design`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `dotnet`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `elixir`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `eventos`                |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `filosofia-y-libros`     |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `front-end`              |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `general`                |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `golang`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `inteligenciaartificial` |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `java`                   |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `javascript`             |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `linux`                  |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `mobile`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `ofertas-de-empleo`      |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `open-english`           |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `php`                    |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `python`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `random`                 |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `ruby-lang`              |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `rust`                   |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `scala`                  |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |
| `work-life`              |    :+1:   |               |      :+1:      |   :+1:    |       :+1:       |    :+1:    |

**Comment by poguez** [comment]
**Propuesta:** tomar decisión de cuales canales depurar con datos de mensajes por canal.

**Comment by poguez** [comment]
**Accionables**
- [x] Crear logging de mensajes.

**Comment by eruizdechavez** [comment]
Voy a mover el codigo del bot al repo de codersmexico para poder contribuir a el entre todos. 

@codersmexico/admins Alguna propuesta para el nombre en lugar de `ChilangoBot`? 

Otros nombres que se me ocurren son `BigBrother` (por eso que todos los mensajes los ve), `Marvin` (referencia al robot paranoico de Hitchhiker's Guide to the Galaxy), `TARDIS` (Doctor Who).

**Comment by eruizdechavez** [comment]
Update: `ChilangoBot` ya esta en todos los canales (tiene un par de issues en las noches, pero ya lo estoy revisando). En un par de semanas deberíamos tener datos de que canales están moviéndose y que canales no.

**Comment by eruizdechavez** [comment]
<img width="276" alt="screen shot 2017-05-05 at 9 00 27 am" src="https://cloud.githubusercontent.com/assets/953140/25748655/71116bb8-3171-11e7-92ea-768c4f19524d.png">

**Comment by eruizdechavez** [comment]
Después de revisar los totales de mensajes en los canales, aquí esta mi propuesta para reducir de 72 a 29 canales. Los que tienen la leyenda _keep?_ son canales que tuvieron entre 0 y 10 mensajes en las ultimas semanas pero sigo pensando que podrían ser de interés. En el caso de `noticias` no veo que aporte nada que no se pueda compartir en `general` o en `random`.

Los canales q mantener abiertos son:

- `android`
- `arquitectura-software`
- `cine-y-series`
- `coders-puebla`
- `comida-y-bebidas`
- `comparte-musica`
- `design`
- `docker (keep?)`
- `dotnet (keep?)`
- `elixir (keep?)`
- `eventos`
- `filosofia-y-libros`
- `front-end`
- `general`
- `golang (keep?)`
- `java (keep?)`
- `javascript`
- `linux`
- `mobile (keep?)`
- `noticias (kill it?)`
- `ofertas-de-empleo`
- `open-english`
- `php (keep?)`
- `python`
- `random`
- `ruby-lang`
- `rust (keep?)`
- `scala`
- `work-life`

Los canales a archivar son:

- `agile`
- `algoritmos`
- `angularjs`
- `aws`
- `big-data`
- `bitcoin-fintech`
- `civic-tech`
- `coders-baja`
- `coders-df`
- `coders-gdl`
- `coders-mty`
- `coders-veracruz`
- `coders-yucatan`
- `compra-venta`
- `consumer-electronics`
- `cybersecurity`
- `deportes`
- `django`
- `escuela-hacker`
- `f-prog`
- `gamedevs`
- `gamers`
- `google-cloud`
- `human-x-interaction`
- `inteligenciartificial`
- `iot`
- `laravel`
- `lectures`
- `mascotas`
- `mucha-lucha`
- `node-js`
- `procrastinacion`
- `regex`
- `shell`
- `spacemacs`
- `splunkers-latam`
- `startup`
- `stickers`
- `swift`
- `teaching`
- `testing`
- `unix`

**Comment by shelldandy** [comment]
Super de acuerdo. Igual darle muerte a noticias

**Comment by poguez** [comment]
**Conteo de mensajes del útimo mes hasta el 30 de junio**
```
general:               506
javascript:            288
work-life:             232
open-english:          149
front-end:             142
ruby-lang:             91
random:                88
scala:                 71
cine-y-series:         68
arquitectura-software: 67
ofertas-de-empleo:     63
coders-puebla:         63
comida-y-bebidas:      55
design:                45
linux:                 33
noticias:              33
python:                32
comparte-musica:       25
filosofia-y-libros:    24
eventos:               24
android:               19
inteligenciartificial: 7
bitcoin-fintech:       6
compra-venta:          5
human-x-interaction:   4
iot:                   4
rust:                  4
regex:                 2
cybersecurity:         2
big-data:              2
algoritmos:            1
gamedevs:              1
aws:                   1
```

**Comment by poguez** [comment]
Me gustaría proponer algunos cambios.

Creo que vale la pena preservar
```
Algoritmos
Cybersecurity
Inteligenciartificial
Linux
```
Podríamos mandar a la congeladora a:
```
docker
django
noticias
```
¿qué opinan?

**Comment by eruizdechavez** [comment]
Descripcion actualizada. Por lo que vi, no hay soporte para checkboxes dentro de la tabla, asi que meti los 👍 . 

Me basta con que pongan su comentario como el de @poguez 👆  y yo actualizo la tabla, o si prefieren pueden editar el issue, copiar la tabla, pegarla en su editor (los indents estan correctos para fuente mono-espaciada) y agregar sus votos.

**Comment by poguez** [comment]
Lunes 5 de junio 11:59PM debemos de tener la votación definitiva.

@diegoaguilar @mike3run @ratacibernetica  @zunware 

Refiéranse al comentario con el que se abrió el issue y voten.

La mitad +1 (personas) aprueban los cambios.

**Comment by eruizdechavez** [comment]
Votación cerrada. Empezando a archivar canales.

**Comment by eruizdechavez** [comment]
Lista la limpieza de canales

**Comment by poguez** [comment]
🙌
